- namespace: "default"
  watchEvent:
    ADDED: true
    MODIFIED: true
    DELETED: false
  fieldSelectors:
    - key: involvedObject.kind
      value: Pod
    - key: reason
      value: Pulled
      type: exclude
    - key: reason
      value: Created
      type: exclude
  extraFilter:
    type: drop
    filters:
      - key: InvolvedObject.Name
        value: batch
        condition: or
      - key: Message
        value: success
        condition: or
- namespace: "kube-system"
  watchEvent:
    ADDED: true
    MODIFIED: true
    DELETED: false
  fieldSelectors:
    - key: involvedObject.kind
      value: Pod
      type: include
    - key: reason
      value: Killing
      type: include
  channel: "system-notice"
  logStream: "custom-stream"
- namespace: ""
  watchEvent:
    ADDED: true
    MODIFIED: true
    DELETED: false
  fieldSelectors:
    - key: involvedObject.kind
      value: Node
      type: include
