- namespace: "default"
  watchEvent:
    ADDED: true
    MODIFIED: true
    DELETED: false
  fieldSelectors:
    - key: involvedObject.kind
      value: Pod
    - key: reason
      value: Pulled
      except: true
    - key: reason
      value: Created
      except: true
- namespace: "kube-system"
  watchEvent:
    ADDED: true
    MODIFIED: true
    DELETED: false
  fieldSelectors:
    - key: involvedObject.kind
      value: Pod
      except: false
    - key: reason
      value: Killing
      except: false
  channel: "system-notice"
  logStream: "custom-stream"
- namespace: ""
  watchEvent:
    ADDED: true
    MODIFIED: true
    DELETED: false
  fieldSelectors:
    - key: involvedObject.kind
      value: Node
      except: false
